### ISSUE TITLE
M4L Device

### ISSUE THREAD

**Issue by offlinemark** [offlinemark/dawtool#11]
Requested here: https://github.com/offlinemark/dawtool/issues/7

**Comment by offlinemark** [comment]
Closing because I won't get to this soon, but please comment or vote to bump.

**Comment by Nickyg001** [comment]
https://maxforlive.com/library/device/8295/exportlocatorids
https://maxforlive.com/library/device/3971/fgc-cuepointexport

these tried to make a device max for live to export the locators, i tried that and it doesn't work well at all.

It can be a first step to be able to implement your script (the best out there so far)
