### ISSUE TITLE
TIMESTAMP incorrect format view!

### ISSUE THREAD

**Issue by Nickyg001** [offlinemark/dawtool#14]
Hi Mark,
a little question!
I use the example script you posted on GITUB, it all works the only thing that the display of the timestamp gives me is in milliseconds I believe (170.8679470269314 ) and not in the format 02:15.115.

How am I supposed to go about getting the 00:00.000 time format right???

THANK YOU

this is the format that the script returns to me now:
------------------------------------
0.0 comfort - Breathwork
170.8679470269314 Yung Lean - Yoshi City
342.787134870338 Bladee - Black Boy
558.3549951350733 Drake - Jumpman
736.0 Skrillex - Scary Monsters and Nice Sprites
953.0376568743757 Rebecca Black - Friday

this is what i would like to get:
-----------------------------------
00:00.000 nciku - peaceofmind
02:15.115 comfort - a n g e l _ w i n g s
05:18.654 rose bride rings - femme fatale
06:52.654 ranov - butterfly
08:47.077 scalade - tempura VIP
10:57.423 mirvs - defrosted

------- CODE USED-------------
import sys
import dawtool

filename = sys.argv[1]
with open(filename, 'rb') as f:
    # Load project based on file extension
    proj = dawtool.load_project(filename, f)
    # Parse project, recompute time markers
    proj.parse()
    # Access project data
    for marker in proj.markers:
        print(marker.time, marker.text)
-----------------------------------------------

**Comment by offlinemark** [comment]
You need to add a line at the top:

from dawtool import format_time

And then change the print line to:

print(format_time(marker.text), marker.time)

:)

**Comment by Nickyg001** [comment]
from dawtool import format_time
....
print(format_time(marker.text), marker.time)

ERROR:    ?????
Traceback (most recent call last):
  File "C:\Users\nicky\Desktop\Nuova cartella (3)\py_scr\DWT_Ableton_LOCATOR.py", line 35, in <module>
    print(marker.time, format_time(marker.text))
  File "C:\Users\nicky\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dawtool\util.py", line 30, in format_time
    total_sec = total_seconds if precise else int(total_seconds)
ValueError: invalid literal for int() with base 10: 'comfort - Breathwork'

**Comment by offlinemark** [comment]
Sorry typo:

print(format_time(marker.time), marker.text)

**Comment by offlinemark** [comment]
Code A is simpler, shorter, but less powerful. You only can access marker
data.

Code B is more complex but more powerful. It is possible to access more
data in the project file. However this is not shown nor documented as of
yet.

**Comment by Nickyg001** [comment]
**Thanks now it works.**

1. A small precision: Even if in final use it still works, the timestamp of the time displays it to me in minutes, it is feasible to display it in Hours:Minutes:Seconds 71:59 ---> 01:11:59.000

2. Is it also possible to write the frames precisely?
%H:%M:%S%.%f ----> 01:11:59.845

3. So CODE B is more powerful, it has more options that can be accessed but these additional functions have not yet been disclosed so powerful yes but the additional powers don't work.
What can be accessed as additional data? (small spoiler)

**Comment by Nickyg001** [comment]
> **Thanks now it works.**
> 
> 1. A small precision: Even if in final use it still works, the timestamp of the time displays it to me in minutes, it is feasible to display it in Hours:Minutes:Seconds 71:59 ---> 01:11:59.000
> 2. Is it also possible to write the frames precisely?
>    %H:%M:%S%.%f ----> 01:11:59.845

dawtool.format_time(marker.time, hours_fmt=True, precise=True), marker.text) 😁😁😁😁😁😁😁😁😁😁😁😁


remains this:
3. So CODE B is more powerful, it has more options that can be accessed but these additional functions have not yet been disclosed so powerful yes but the additional powers don't work.
What can be accessed as additional data? (small spoiler)

**Comment by offlinemark** [comment]
You found it! Well done!! :D 

> 3. So CODE B is more powerful, it has more options that can be accessed but these additional functions have not yet been disclosed so powerful yes but the additional powers don't work.
> What can be accessed as additional data? (small spoiler)

It depends on the DAW format. For Ableton, it is not so much. BPM and tempo automation data. 

While it is undocumented, you can see what it available in the source code:

https://github.com/offlinemark/dawtool/blob/master/dawtool/daw/ableton.py#L151-L156

So then you can do things like

```
print(proj.beats_per_min)
print(proj.tempo_automation_events)

```
