### ISSUE TITLE
hello, Shall we update this awesome script?

### ISSUE THREAD

**Issue by Nickyg001** [offlinemark/dawtool#6]
The script is great, I have some ideas to extend this script (but I'm not capable as a non-programmer).

1. I'd like this script to become a software that is also unrelated to the website function, therefore also functioning offline.
2. Exporting the locators to a marker compatible CSV file for Adobe Audition would be useful (so you can store the markers directly in the mp3 file)

**Comment by offlinemark** [comment]
Thanks @Nickyg001. For the moment, running and maintaining the https://timestamps.me service is the best I can offer for free development effort. I'm happy to consider other features if there is sufficient demand.

 > I'd like this script to become a software that is also unrelated to the website function, therefore also functioning offline.

Please note that this `dawtool` repository does work entirely offline, although the user interface is not very friendly.

I made two separate issues to track these two separate requests and will close this - thanks.

**Comment by Nickyg001** [comment]
![image](https://user-images.githubusercontent.com/33684734/207549539-73a08ca4-d2db-4a73-9a99-d65b62aee69f.png)
does dawtool really work locally?
Could you make a guide on how to make it work? I've been trying for days but I only get errors, and "pip install git+https://github.com/offlinemark/dawtool"

**Comment by offlinemark** [comment]
@Nickyg001 Thanks for reporting. I just pushed a fix, can you please try again?

**Comment by Nickyg001** [comment]
It doesn't give me errors this time but I would like to understand how to make DAWTOOL work locally.
I wrote a post today about it.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/33684734/211408312-0d31b610-f9b8-4dee-be5b-4a7757ebc550.png">
