### ISSUE TITLE
tool for max for live??

### ISSUE THREAD

**Issue by Nickyg001** [offlinemark/dawtool#7]
Wouldn't it be better to develop a MAX FOR LIVE Device to export the Locators list?

like this one (but it doesn't work, at least it doesn't work for me at all)
https://maxforlive.com/library/device/8295/exportlocatorids

I would also add other features, such as:

1. Template Customization Export template

00:00:00 - landlord name
01. lessor name [00:00:00]
and other variants that the user can decide

2. Export in different formats, txt, csv, cue....

3. Export compatible with other editing software such as AUDITION which accepts a specific csv.

**Comment by offlinemark** [comment]
I've made separate issues to track these requests. Unfortunately I won't get to these soon unless there is significant demand. Wish I could!
